---
- hosts: Tomcat
  become: yes
  gather_facts: False
  tasks:

  - name: Install java_1.8
    apt: name=openjdk-8-jdk state=present

  - name: Install tomcat
    get_url: url=https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.64/bin/apache-tomcat-8.5.64.tar.gz dest=/home/ansadmin
    
  - name: unarchieve tomcat
    unarchive:
      src= /home/ansadmin
      dest= /home/ansadmin
      remote_src= yes

  - name: Download latest VProfile.war file
    get_url: url=http://{{nexusip}}:8081/nexus/content/repositories/VProfile-repo/{{groupid}}/{{time}}/{{build}}/{{vprofile_version}} dest=/tmp/ mode=755

  - name: stop tomcat
    shell: nohup /home/ansadmin/apache-tomcat-8.5.64/bin/shutdown.sh &

  - name: Copy artifact to tomcat folder
    shell: cp /tmp/{{vprofile_version}} /var/lib/tomcat/webapps

  - name: Delete link to existing vprofile version
    file: path=/var/lib/tomcat/webapps/VProfile state=absent

  - name: start tomcat
    shell: nohup /home/ansadmin/apache-tomcat-8.5.64/bin/startup.sh &
  - wait_for: path=/var/lib/tomcat/webapps/{{time}}-{{build}}

  - name: Link latest vprofile version
    file: src=/var/lib/tomcat/webapps/{{time}}-{{build}} dest=/var/lib/tomcat/webapps/VProfile state=link

  - name: Stop iptables
    service: name=iptables state=stopped

